#spring:
#  datasource:
#    username:root
#    password:
#    url:jdbc:mysql://localhost:3306/petit
#    driver-class-name:com.mysql.cj.jdbc.Driver
#
#jpa:
#  show-sql: true
#  hibernate:
#    ddl-auto:update
#  properties.hebernate.dialect:org.hibernate.dialect.mysql5dialect
